name: Sample Playwright Cucumber Framework

on: [push]

jobs:
  sample-playwright-cucumber-framework:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install

      - name: Execute All Tests
        run: | 
          browser=chrome npm run cucumber -- --tags="@test" --parallel=5
          node cucumber.config.js
      
      - name: Archive Test Result
        uses: actions/upload-artifact@v4
        with:
          name: Result
          path: reports/